"""Add chat_title column to reminders

Revision ID: aee009efa436
Revises: cf19f441a84c
Create Date: 2025-06-29 10:16:55.042644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee009efa436'
down_revision: Union[str, None] = 'cf19f441a84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('chat_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'chat_title')
    # ### end Alembic commands ###
